# Training and testing of Convolutional neural network

Here, all the required libraries are added and then saved X and y are loaded with the help of pickle. Then, the X and y are converted into numpy arrey to feed into Convolutional neural network.

In [89]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Conv2D, MaxPooling2D, Flatten
import pickle
import numpy as np

X = pickle.load(open("X.pickle","rb"))    #loading X file from X.pickle
y = pickle.load(open("y.pickle","rb"))    #loading y file from y.pickle

X= X/255.0                    #deviding X by 255 to neutralize it

X = np.array(X)               #converting X into numpy array
y = np.array(y)               #converting y into numpy array

Here, keras Sequential model has been used to make Convolutional neural network. There are two convolutional layers with the 64 neurons each and with (3,3) window size. The activation function in both convolutional layers is "relu". Then MaxPooling2D is used in both of the convolutional layers with pool size of (2,2). Then there is one Dense layer of 64 neurons and before that flatten is used because the Dense layer only accepts 1D data. The output layer is also a Dense layer with "softmax" activation and 6 neurons. Then in "model.compile", "sparse_categorical_crossentropy" is used to reduce loss, "adam" is used as an optimizer and 'accuracy' is used for metrics. Then validation split is 0.1, epochs is 5 and batch size is 32 in the training of the model.

In [90]:
model = Sequential()                                #making keras sequential model
model.add(Conv2D(64,(3,3), input_shape =X.shape[1:])) #Adding convolutional neural network with window size of (3,3) and 64 neurons
model.add(Activation("relu"))                         #Adding activation function as "relu"    
model.add(MaxPooling2D(pool_size=(2,2)))              #Adding pooling layer with pool size of (2,2) and pooling function of MaxPoolin2D

model.add(Conv2D(64,(3,3), input_shape =X.shape[1:])) #Adding convolutional neural network with window size of (3,3) and 64 neurons
model.add(Activation("relu"))                         #Adding activation function as "relu"
model.add(MaxPooling2D(pool_size=(2,2)))              #Adding pooling layer with pool size of (2,2) and pooling function of MaxPoolin2D

model.add(Flatten())                         #Adding layer to flatten the data
model.add(Dense(64))                         #Adding Dense layer with 64 neurons

model.add(Dense(6))                          #Adding output layer with 6 neurons 
model.add(Activation("softmax"))             #Adding activation function of "softmax" to the output layer

model.compile(loss = "sparse_categorical_crossentropy", #minimizing loss with "sparse_categorical_crossentropy"
             optimizer = "adam",                        #optimizing with "adam"
             metrics =['accuracy'])                     #Adding metrics as 'accuracy'

model.fit(X, y, batch_size=32, validation_split =0.1, epochs =5) #selecting batch size of 32, validation split of 0.1 and 5 epochs

Train on 12630 samples, validate on 1404 samples
Epoch 1/5
12630/12630 [==============================] - 239s 19ms/sample - loss: 1.2247 - accuracy: 0.5290 - val_loss: 0.9551 - val_accuracy: 0.6311
Epoch 2/5
12630/12630 [==============================] - 238s 19ms/sample - loss: 0.7680 - accuracy: 0.7162 - val_loss: 0.6918 - val_accuracy: 0.7443
Epoch 3/5
12630/12630 [==============================] - 241s 19ms/sample - loss: 0.5825 - accuracy: 0.7918 - val_loss: 0.6915 - val_accuracy: 0.7443
Epoch 4/5
12630/12630 [==============================] - 243s 19ms/sample - loss: 0.4095 - accuracy: 0.8605 - val_loss: 0.7853 - val_accuracy: 0.7279
Epoch 5/5
12630/12630 [==============================] - 246s 19ms/sample - loss: 0.2402 - accuracy: 0.9188 - val_loss: 0.8173 - val_accuracy: 0.7472


Now, After getting the optimum result by changing the number of layers and number of neurons, the keras model with its optimum result is saved in "HDF5" file with "model.save" and "h5py". Also loading the same model with "load_model".

In [91]:
import h5py                         #importing h5py                   
from keras.models import load_model #importing load_model
model.save('my_model3.h5')         #saving model in "HDF5" file as "my_model3.h5"
del model                          #deleting existing models

In [96]:
# loading the saved model 
classifierLoad = tf.keras.models.load_model('/Users/vishvmac/Machine Learning/Machine learning projects/Intel image classification dataset/my_model3.h5')


Now, loading the test dataset, with "pickle.load" that has been saved before. 

In [97]:
X_test = pickle.load(open("X_test.pickle","rb"))      #loading X_test file from X_test.pickle
y_test = pickle.load(open("y_test.pickle","rb"))      #loading y_test file from y_test.pickle

Now, loading the libraries of "sklearn.metrics" to get the "confusion matrix" and "accuracy score". And getting the rounded predictions as the direct predictions from the model will be probabilities of different classes. and then printing confusion metrics as cm and accuracy score as acc_score.

In [98]:
from sklearn.metrics import confusion_matrix        #importing "confusion_matrix" from "sklearn.metrics" 
from sklearn.metrics import accuracy_score          #importing "accuracy_score" from "sklearn.metrics" 

X_test = tf.cast(X_test, tf.float32)                #converting X_test into float32.
rounded_predictions = classifierLoad.predict_classes(X_test,batch_size=32 ,verbose=0) #getting rounded predictions from model
    
cm = confusion_matrix(y_test, rounded_predictions)  #getting confusion matrix 
acc_score = accuracy_score(y_test, rounded_predictions) #getting accuracy score


In [95]:
print(cm,acc_score)  #printing confusion matrix and accuracy score

[[224   9  85  25  27  67]
 [ 13 376  51   9   6  19]
 [  4   0 481  55  13   0]
 [  8   4 257 243   7   6]
 [ 13   0 248  89 150  10]
 [ 69  29  93  16   8 286]] 0.5866666666666667
